# -*- coding: utf-8 -*-
"""autoCorrect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19kcP_wpSmDsLN9pK8M6nfyeCch3eaiEK
"""

pip install textblob

pip install spello

from spello.model import SpellCorrectionModel

sp = SpellCorrectionModel(language = 'en')

with open('/content/drugs.txt',"r") as file:
     data = file.readlines()

data

sp.train(data)

sp.spell_correct("paractmal")

